name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Which area does this feature relate to?
      multiple: true
      options:
        - Frontend/UI
        - Backend/API
        - Machine Learning
        - Data Pipeline/ETL
        - Performance
        - Documentation
        - DevOps/Deployment
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Other solutions or features you've considered
      placeholder: Alternative approaches...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to contribute this feature?
      description: Check if you're willing to work on implementing this feature
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
